### ISSUE TITLE
ImportError: No module named 'line_variance_parallel'

### ISSUE THREAD

**Issue by niecongchong** [fidler-lab/defgrid-release#3]
```
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/line_variance_parallel/build.ninja...
Building extension module line_variance_parallel...
1.10.0.git.kitware.jobserver-1
Loading extension module line_variance_parallel...
Traceback (most recent call last):
  File "scripts/train/train_def_grid_full.py", line 21, in <module>
    from Models.deformable_grid import DeformableGrid
  File "/apdcephfs/private_nickccnie/wrpaper/Code/defgrid/Models/deformable_grid.py", line 9, in <module>
    from layers.DefGrid.diff_variance import LatticeVariance
  File "/apdcephfs/private_nickccnie/wrpaper/Code/defgrid/layers/DefGrid/diff_variance.py", line 10, in <module>
    from layers.DefGrid.variance_function_atom.line_distance_func_parallel.utils import variance_f_in_one_atom_parallel as line_variance_parallel
  File "/apdcephfs/private_nickccnie/wrpaper/Code/defgrid/layers/DefGrid/variance_function_atom/line_distance_func_parallel/utils.py", line 13, in <module>
    verbose=True)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/cpp_extension.py", line 877, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/cpp_extension.py", line 1084, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/usr/lib64/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'line_variance_parallel'
```

**Comment by SteveJunGao** [comment]
Can you show you PyTorch version and CUDA version? It seems you didn't successfully compile the cuda extension `line_variance_parallel`

**Comment by niecongchong** [comment]
You are right, the essential reason for the error is that the cuda extension was not compiled successfully. 
I have changed the pytorch version to 1.2.0 and the cuda version to 10.1. 
In addition, the ninja version is 1.9.0. 
Except for line_variance_parallel, the other cuda extensions did not fail.

**Comment by niecongchong** [comment]
Line 118 of your code `diff_variance.py` about `line_variance_paralel` is commented out. I solved this problem by commenting out the import part accordingly
