### ISSUE TITLE
pytorch cpp extensions

### ISSUE THREAD

**Issue by iszihan** [fidler-lab/defgrid-release#5]
Hello, I got an error from running the training script that says:

Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/mean_feature/build.ninja...
Building extension module mean_feature...
Traceback (most recent call last):
  File "scripts/train/train_def_grid_full.py", line 21, in <module>
    from Models.deformable_grid import DeformableGrid
  File "/home/selenaling/Desktop/defgrid-release/Models/deformable_grid.py", line 9, in <module>
    from layers.DefGrid.diff_variance import LatticeVariance
  File "/home/selenaling/Desktop/defgrid-release/layers/DefGrid/diff_variance.py", line 8, in <module>
    from layers.DefGrid.mean_feature.mean_feature import get_grid_mean_feature
  File "/home/selenaling/Desktop/defgrid-release/layers/DefGrid/mean_feature/mean_feature.py", line 11, in <module>
    verbose=True)
  File "/home/selenaling/anaconda3/envs/defgrid27/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 658, in load
    is_python_module)
  File "/home/selenaling/anaconda3/envs/defgrid27/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "/home/selenaling/anaconda3/envs/defgrid27/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 880, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/selenaling/anaconda3/envs/defgrid27/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 972, in _build_extension_module
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3915: ordinal not in range(128)

Am wondering if this is encountered before and how can I solve it? I am running with python2.7. Thank you in advance!

**Comment by iszihan** [comment]
The above error is resolved using python 3.6. However, there are a lot more errors compiling the mean_features cpp/cu codes. Posting one of them for reference. 

/home/selenaling/anaconda3/envs/defgrid/lib/python3.7/site-packages/torch/include/ATen/core/TensorMethods.h:1566:176:   required from here
/usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                                                   ^~~~~
/usr/include/c++/6/tuple:484:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }

Any tip of resolving these errors will be much appreciated! : )

**Comment by SteveJunGao** [comment]
Hi,

I think the main reason why the problem happened is the mismatch between the CUDA version in the PyTorch and the cuda version in the Linux system, can you check which PyTorch version you are using and also the cuda version PyTorch is using by running: 
```python
import torch
print(torch.__version__)
print(torch.version.cuda)
```
and compare it with the cuda version of the system, (typically running `nvidia-smi` or `nvcc --version` in the Linux terminal).

**Comment by iszihan** [comment]
That fixed it. Thank you so much!
